name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:       
       - name: Checkout Repo
         uses: actions/checkout@v3
       - name: Install Node
         uses: actions/setup-node@v3
         with:
          node-version: 'lts/*'
       - run: npm install 
    
  job2:
    need: job1
    runs-on: ubuntu-latest
    steps:       
       - name: Checkout Repo
         uses: actions/checkout@v3
       - name: Install Node
         uses: actions/setup-node@v3
         with:
          node-version: 'lts/*'
       - run: npm test 
